In [ ]:
from pathlib import Path
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    recall_score,
    precision_score,
    f1_score
)

Vamos baixar as bases de treino e teste para trabalharmos

In [ ]:
pasta_saida = Path("dados/processed/splits")

x_treino_smote = pd.read_csv(pasta_saida / "x_treino_smote.csv")
x_treino_scaled_smote = pd.read_csv(pasta_saida / "x_treino_scaled_smote.csv")

x_teste = pd.read_csv(pasta_saida / "x_teste.csv")
x_teste_scaled = pd.read_csv(pasta_saida / "x_teste_scaled.csv")

y_treino_smote = pd.read_csv(pasta_saida / "y_treino_smote.csv")["internacao_prolongada"]
y_treino_scaled_smote = pd.read_csv(pasta_saida / "y_treino_scaled_smote.csv")["internacao_prolongada"]

y_teste = pd.read_csv(pasta_saida / "y_teste.csv")["internacao_prolongada"]

Criamos uma função para salvar os resultados dessa fase

In [ ]:
resultados_ajustado = []

def salvar_resultados_ajustado(nome_modelo, y_real, y_pred): 
    tn, fp, fn, tp = confusion_matrix(y_real, y_pred).ravel()
    
    resultados_ajustado.append({
        'Modelo': nome_modelo,
        'Accuracy': accuracy_score(y_real, y_pred),
        'Recall': recall_score(y_real, y_pred),
        'Precision': precision_score(y_real, y_pred),
        'F1-score': f1_score(y_real, y_pred),
        'Verdadeiros Negativos': tn,
        'Falsos Positivos': fp,
        'Falsos Negativos': fn,
        'Verdadeiros Positivos': tp
    })

Nessa fase usaremos os 3 modelos com melhor desempenho na fase anterior, que são:

1. Regressão Logística com SMOTE: teve o melhor f1-score da tabela e o segundo melhor recall sendo o modelo com melhor equilibrio geral entre encontrar casos positivos e manter uma precisão aceitavel

2. Random Forest com SMOTE: Segundo melhor f1-score e melhor precisão entre os modelos com SMOTE tendo o desempenho mais equilibrado que o XGBoost SMOTE

3. XGBoost com SMOTE: Melhor recall da tabela, indentificando mais casos positivos mesmo com a precisão menor, valendo a pena avançar pois reduz bastante os falsos negativos

eu irei fazer um ajuste de hiperparametros que eu considero o basico para cada modelo, e apos observar seus respectivos desempenhos, leveramos o modelo para a ultima fase onde realizaremos um ajuste mais pesado de hiperparametros visando ter um melhor desempenho

# Regressão Logística com SMOTE Ajustado

In [3]:
modelo_reglog_ajustado = LogisticRegression(
    C=0.5,
    solver="lbfgs",
    max_iter=1000,
    random_state=42
)

modelo_reglog_ajustado.fit(x_treino_scaled_smote, y_treino_scaled_smote)

LogisticRegression(C=0.5, max_iter=1000, random_state=42)

Fazendo previsões

In [4]:
y_pred_reglog_smote_ajustado = modelo_reglog_ajustado.predict(x_teste_scaled)

Avaliamos o modelo

In [5]:
print('Matriz de confusão:')
print(confusion_matrix(y_teste, y_pred_reglog_smote_ajustado))

print('\nClassification Report:')
print(classification_report(y_teste, y_pred_reglog_smote_ajustado))

print('Accuracy:', accuracy_score(y_teste, y_pred_reglog_smote_ajustado))
print('Recall:', recall_score(y_teste, y_pred_reglog_smote_ajustado))
print('Precision:', precision_score(y_teste, y_pred_reglog_smote_ajustado))
print('F1-score:', f1_score(y_teste, y_pred_reglog_smote_ajustado))

Matriz de confusão:
[[160249  43442]
 [ 14530  40157]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.79      0.85    203691
           1       0.48      0.73      0.58     54687

    accuracy                           0.78    258378
   macro avg       0.70      0.76      0.71    258378
weighted avg       0.82      0.78      0.79    258378

Accuracy: 0.7756310521793651
Recall: 0.7343061422275861
Precision: 0.48035263579707893
F1-score: 0.5807818578887234

O modelo apresentou recall d aproximadamente 73,34% para a classe 1, identificando corretamente 40107 das 54687 internações prolongadas.

comparada com a versão anterior sem ajuste, houve uma pequena melhora no recall, indicando que o modelo ficou ligeiramente mais sensivel a detectar internações prolongadas apesar dessa melhora vir acompanhada de uma leve redução na precision e no f1-score

a precision para a classe 1 foi de aproximadamente 48,08%, indicando que entre os casos classificados como internação prolongada, cerca de 48% realmente pertenciam a classe 1. já o f1-score foi de aproximadamente 58,08%, valor muito proximo ao modelo com configuração padrão

de forma geral os ajustes não trouxeram ganho expressivo ao modelo, por isso essa versão pode ser considerada interessante caso o objetivo seja priorizar a detecção de internações prolongadas, mas não representa uma melhora clara no equilibrio geral do modelo

In [11]:
salvar_resultados_ajustado('Regressão Logística Ajustada', y_teste, y_pred_reglog_smote_ajustado)

In [12]:
resultados_modelos_ajustados = pd.DataFrame(resultados_ajustado)
resultados_modelos_ajustados

,Modelo,Accuracy,Recall,Precision,F1-score,Verdadeiros Negativos,Falsos Positivos,Falsos Negativos,Verdadeiros Positivos
0,Regressão Logística Ajustada,0.775631,0.734306,0.480353,0.580782,160249,43442,14530,40157

# Random Forest com SMOTE ajustado

In [6]:
modelo_random_forest_smote_ajustado = RandomForestClassifier(
    n_estimators=250,
    max_depth=12,
    min_samples_split=20,
    min_samples_leaf=10,
    max_features="sqrt",
    bootstrap=True,
    random_state=42,
    n_jobs=-1
)

modelo_random_forest_smote_ajustado.fit(x_treino_smote, y_treino_smote)

RandomForestClassifier(max_depth=12, min_samples_leaf=10, min_samples_split=20,
                       n_estimators=250, n_jobs=-1, random_state=42)

agora fazemos algumas previsões

In [7]:
y_pred_random_forest_smote_ajustado = modelo_random_forest_smote_ajustado.predict(x_teste)

Agora avaliamos o modelo

In [8]:
print('Matriz de confusão:')
print(confusion_matrix(y_teste, y_pred_random_forest_smote_ajustado))

print('\nClassification Report:')
print(classification_report(y_teste, y_pred_random_forest_smote_ajustado))

print('Accuracy:', accuracy_score(y_teste, y_pred_random_forest_smote_ajustado))
print('Recall:', recall_score(y_teste, y_pred_random_forest_smote_ajustado))
print('Precision:', precision_score(y_teste, y_pred_random_forest_smote_ajustado))
print('F1-score:', f1_score(y_teste, y_pred_random_forest_smote_ajustado))

Matriz de confusão:
[[133773  69918]
 [ 12986  41701]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.66      0.76    203691
           1       0.37      0.76      0.50     54687

    accuracy                           0.68    258378
   macro avg       0.64      0.71      0.63    258378
weighted avg       0.80      0.68      0.71    258378

Accuracy: 0.6791367686103306
Recall: 0.7625395432186809
Precision: 0.3736012686012238
F1-score: 0.5014972400274194

O modelo apresentou um aumento expressivo da classe 1, identificando 42324 das 54687 internações prolongadas presentes, tendo um recall de 77,39%, indicando que o modelo passou a detectar uma proporção relativamente maior dos casos de internações prolongadas

apesar disso, essa melhora veio seguida de uma queda na metrica precision da classe 1, causado pelo aumeto de falsos positivos obtendo agora 65708 casos, ou seja ele classificou muitos internações não prolongadas como prolongadas

o f1-score da classe 1 foi de aproximadamenre 52,02%, levemente inferior ao resultado obtido pelo modelo sem ajustes indicando um aumento de desequilibrio entre recall e precision

em suma, o modelo se tornou mais sensivel a classe de interesse, mas tambem aumentou excessivamente os falsos positivos, com isso não superando sua versão não ajustada

In [13]:
salvar_resultados_ajustado('Random Forest Ajustado', y_teste, y_pred_random_forest_smote_ajustado)

In [14]:
resultados_modelos_ajustados = pd.DataFrame(resultados_ajustado)
resultados_modelos_ajustados

,Modelo,Accuracy,Recall,Precision,F1-score,Verdadeiros Negativos,Falsos Positivos,Falsos Negativos,Verdadeiros Positivos
0,Regressão Logística Ajustada,0.775631,0.734306,0.480353,0.580782,160249,43442,14530,40157
1,Random Forest Ajustado,0.679137,0.762540,0.373601,0.501497,133773,69918,12986,41701

# XGBoost com SMOTE Ajustado

In [15]:
modelo_xgboost_smote_ajustado = XGBClassifier(
    n_estimators=150,
    max_depth=4,
    learning_rate=0.07,
    min_child_weight=5,
    gamma=0.2,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=2,
    reg_alpha=0,
    random_state=42,
    n_jobs=-1,
    eval_metric="logloss"
)

modelo_xgboost_smote_ajustado.fit(x_treino_smote, y_treino_smote)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0.2,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.07, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=150, n_jobs=-1,
              num_parallel_tree=None, ...)

Agora fazemos algumas previsões

In [16]:
y_pred_xgboost_smote_ajustado = modelo_xgboost_smote_ajustado.predict(x_teste)

Agora avaliamos o modelo

In [17]:
print('Matriz de confusão:')
print(confusion_matrix(y_teste, y_pred_xgboost_smote_ajustado))

print('\nClassification Report:')
print(classification_report(y_teste, y_pred_xgboost_smote_ajustado))

print('Accuracy:', accuracy_score(y_teste, y_pred_xgboost_smote_ajustado))
print('Recall:', recall_score(y_teste, y_pred_xgboost_smote_ajustado))
print('Precision:', precision_score(y_teste, y_pred_xgboost_smote_ajustado))
print('F1-score:', f1_score(y_teste, y_pred_xgboost_smote_ajustado))

Matriz de confusão:
[[142807  60884]
 [ 12553  42134]]

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.70      0.80    203691
           1       0.41      0.77      0.53     54687

    accuracy                           0.72    258378
   macro avg       0.66      0.74      0.66    258378
weighted avg       0.81      0.72      0.74    258378

Accuracy: 0.7157768850289111
Recall: 0.7704573298955876
Precision: 0.4089964860509814
F1-score: 0.5343394312165118

O modelo identificou 42134 das 54687 internações prolongadas, resultando em um recall de aproximadamente 77,05% para a classe 1

apesar disso a versão ajustada do modelo apresentou queda em relação ao modelo original tendo as 3 metricas principais inferiores ao modelo anterior

a precision da classe 1 ficou em aproximadamenre 40,90%, indicando que ele gerou muitos falsos positivos mostrando que o modelo continuou sensivel a classe 1, mas com baixa capacidade de separar corretamente os casos prolongados dos não prolongados

o f1-score da classe 1 foi aproximadamente 53,43%, inferior ao resultado obtido pelo modelo não ajustado, ou seja apesar do recall elevado, o ajuste de hiperparametros não melhorou o equilibrio entre recall e precision

em suma, a versão ajustada do modelo é inferior ao modelo original

In [18]:
salvar_resultados_ajustado('XGBoost Ajustado', y_teste, y_pred_xgboost_smote_ajustado)

In [19]:
resultados_modelos_ajustados = pd.DataFrame(resultados_ajustado)
resultados_modelos_ajustados

,Modelo,Accuracy,Recall,Precision,F1-score,Verdadeiros Negativos,Falsos Positivos,Falsos Negativos,Verdadeiros Positivos
0,Regressão Logística Ajustada,0.775631,0.734306,0.480353,0.580782,160249,43442,14530,40157
1,Random Forest Ajustado,0.679137,0.762540,0.373601,0.501497,133773,69918,12986,41701
2,XGBoost Ajustado,0.715777,0.770457,0.408996,0.534339,142807,60884,12553,42134

Com isso podemos observar que

1. Regressão Logistica ajustada teve o melhor desempenho geral entre modelos avaliados. apesar de não ter obtido o maior recall, apresentou o mais f1-score e a melhor precision, mantendo ainda uma boa capacidade de identificar internações prolongadas nos indicando que o modelo conseguiu equilibrar melhor a detecção da classe de interesse com uma quantidade menor de falsos positivos.

2. Random Forest ajustado apresentou recall elevado, identificando uma quantidade relevante de internações prolongadas. porem, sua precision foi a mais baixa entre os 3 modelos, indicando que ele classificou muitos casos não prolongados como prolongados. como consequencia, seu f1-score foi inferior ao dos demais modelos, mostrando menor equilibrio entre recall e precision

3. XGBoost ajustado apresentou maior recall entre os modelos avaliados, sendo o que mais identificou corretamente internações prolongadas. porem, sua precision foi inferior à da Regressão Logistica ajustada, indicando maior numero de falsos positivos. ainda assin, seu desempenho foi superior ao Random Forest ajustado em f1-score, tornando uma opção interessante para ajustes posteriores

em suma, Regressão logistica ajustada foi o melhor modelo nesta etapa, levando em conta o equilibrio entre recall, precision e f1-score. O XGBoost ajustado teve alto recall e apresenta uma maior possibilidade de ajustes de hiperparametros, permanecendo como melhor candidato para a etapa de ajustes mais finos. já o Random Forest ajustado teve um desempenho pior em equilibrio geral, principalmente devido a baixa precision e ao elevado numero de falsos positivos

com isso em mente, embora a Regressão Logistica ajustada tenha um melhor desempenho geral nesta etapa, com maior f1-score, ou seja, equilibrio geral entre recall e precision, decidimos levar a frente o XGBoost ajustado para a proxima fase de ajuste de hiperparametros

essa escolha foi tomada pelo fato do XGBoost apresentar maior quantidade de hiperparametros capazes de controlar a complexidade do modelo, a profundidade das arvores, a criação de novas divisões e a regularização, apresentando maior potencial de melhoria por meio de ajuste fino.

Assim sendo, a proxima etapa terá como objetivo verificar se é possivel reduzir os falsos positivos e melhorar a precision e o f1-score do xgboost, sem perder excessivamente o recall da classe 1. a Regressão Logistica Ajustada será usada como modelo de referencia, por ter sido o melhor modelo até o momento em termos de equilibrio geral.

In [21]:
# vou salvar a tabela com os resultados tambem
resultados_modelos_ajustados.to_csv("dados/processed/resultados/resultados_modelos_ajustados.csv", index=False)